name: Terraform Deploy

on:
  workflow_dispatch:

env:
  TF_VERSION: '1.6.6'

jobs:
  terraform-init:
    name: Terraform Init
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init

    # Add a step to list files for debugging
    - name: List Terraform files
      run: ls -la .terraform .terraform.lock.hcl terraform.tfstate || echo "Files not found"

    - name: Upload .terraform and tfstate
      uses: actions/upload-artifact@v4
      with:
        name: terraform-init-data
        path: |
          .terraform/
          .terraform.lock.hcl
          terraform.tfstate
        if-no-files-found: error # Fail the step if no files are found

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: terraform-init
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download init artifacts
      uses: actions/download-artifact@v4
      with:
        name: terraform-init-data
        path: .

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Upload Plan File
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: tfplan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment:
      name: prod-approval
      url: https://portal.azure.com/
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Plan File
      uses: actions/download-artifact@v4
      with:
        name: tfplan
        path: .

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
